### ISSUE TITLE
[Bug]: Revise Bandit configuration and skipped rules: skips = B101,B404,B603,B607

### ISSUE THREAD

**Issue by kse3hi** [eclipse-velocitas/devenv-runtimes#33]
### Severity

High

### What release version, tag or commit-hash did you use?

https://github.com/eclipse-velocitas/devenv-runtimes/blob/v2.0.0

### Current Behavior

Bandit skips next rules: skips = B101,B404,B603,B607

### Steps to Reproduce

1. Go to https://github.com/eclipse-velocitas/devenv-runtimes/blob/main/setup.cfg
2. Check section [bandit]

### Expected Behavior

Bandit shall not skip rules or rational shall be given.

### Possible Solution

E.g. for B101 proper configuration of test sources shall be given and no assertion shall be used in productive code.
B404 can be avoided
B603 - analyze deeply
B607 - use properly

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MP91** [comment]
Bandit is completely removed in #57

@kse3hi please check if this can be closed

**Comment by kse3hi** [comment]
LGTM
