### ISSUE TITLE
[Bug]: Hardcoded python-template path in kanto deployment configs

### ISSUE THREAD

**Issue by dennismeister93** [eclipse-velocitas/devenv-runtimes#51]
### Severity

Medium

### What release version, tag or commit-hash did you use?

v2.2.2

### Current Behavior

For the kanto runtime there are hardcoded python template paths configured

### Steps to Reproduce

https://github.com/eclipse-velocitas/devenv-runtimes/blob/83411f068b789b67e18e037308fbd21d70192f20/runtime_kanto/src/runtime/deployment/feedercan.json#L9

https://github.com/eclipse-velocitas/devenv-runtimes/blob/83411f068b789b67e18e037308fbd21d70192f20/runtime_kanto/src/runtime/deployment/mockservice.json#L9

### Expected Behavior

The config should not rely on a hardcoded path because the user could name his repository differently.

Same applies when coming from the new [vehicle-app-template](https://github.com/eclipse-velocitas/vehicle-app-template)

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MP91** [comment]
The files are adapted in the code see: https://github.com/eclipse-velocitas/devenv-runtimes/blob/83411f068b789b67e18e037308fbd21d70192f20/runtime_kanto/src/runtime/runtime_kanto.py#L76
